/**
 * Remaining EPL Fixtures — 2025/26 Season (GW34–GW38)
 *
 * Title race:     Man City vs Arsenal – both on 70 pts, GD +37, 5 games remaining
 * Relegation:     Tottenham (18th, 31pts) vs West Ham (17th, 33pts) – 2pt gap, 5 games each
 *
 * Each match now maps to 4 possible outcomes:
 *   - Arsenal Title / City Title (The Title Race)
 *   - Spurs Relegated / Spurs Survive (The Relegation Battle)
 */

import type { Match } from './ahp.ts';

export const REMAINING_MATCHES: Match[] = [

  // ── GW34 – Apr 26 ────────────────────────────────────────────────────────
  {
    id: 'gw34-west-ham-everton',
    label: 'West Ham vs Everton',
    gameweek: 34,
    date: '2026-04-26',
    homeTeam: 'West Ham United',
    awayTeam: 'Everton',
    homeColor: '#7A263A',
    awayColor: '#003399',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'West Ham win moves them further from the drop zone.',
    spursSurviveContext:   'Everton win keeps West Ham within Spurs\' reach.',
  },
  {
    id: 'gw34-arsenal-newcastle',
    label: 'Arsenal vs Newcastle',
    gameweek: 34,
    date: '2026-04-26',
    homeTeam: 'Arsenal',
    awayTeam: 'Newcastle United',
    homeColor: '#EF0107',
    awayColor: '#241F20',
    helpsArsenalTitle:   'home',
    helpsCityTitle:      'away',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'Must-win for Arsenal to keep pace with City.',
    cityTitleContext:    'City hope Newcastle can derail the Gunners.',
    spursRelegatedContext: 'No relegation implications.',
    spursSurviveContext:   'No relegation implications.',
  },
  {
    id: 'gw34-wolves-tottenham',
    label: 'Wolves vs Tottenham',
    gameweek: 34,
    date: '2026-04-26',
    homeTeam: 'Wolverhampton Wanderers',
    awayTeam: 'Tottenham Hotspur',
    homeColor: '#FDB913',
    awayColor: '#132257',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'No direct title implications here.',
    cityTitleContext:    'No direct title implications here.',
    spursRelegatedContext: 'A Wolves win drops Spurs deeper into the drop zone.',
    spursSurviveContext:   'A Spurs away win is essential for their survival hopes.',
  },

  // ── GW35 – May 3 & 5 ─────────────────────────────────────────────────────
  {
    id: 'gw35-brentford-west-ham',
    label: 'Brentford vs West Ham',
    gameweek: 35,
    date: '2026-05-03',
    homeTeam: 'Brentford',
    awayTeam: 'West Ham United',
    homeColor: '#E30613',
    awayColor: '#7A263A',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'away',
    helpsSpursSurvive:   'home',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'Away win secures West Ham\'s position.',
    spursSurviveContext:   'Brentford win helps keep West Ham in the relegation scrap.',
  },
  {
    id: 'gw35-arsenal-fulham',
    label: 'Arsenal vs Fulham',
    gameweek: 35,
    date: '2026-05-03',
    homeTeam: 'Arsenal',
    awayTeam: 'Fulham',
    homeColor: '#EF0107',
    awayColor: '#000000',
    helpsArsenalTitle:   'home',
    helpsCityTitle:      'away',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'Home win keeps Arsenal level with City.',
    cityTitleContext:    'Any Arsenal slip hands the advantage to City.',
    spursRelegatedContext: 'No bearing on Spurs survival.',
    spursSurviveContext:   'No bearing on Spurs survival.',
  },
  {
    id: 'gw35-aston-villa-tottenham',
    label: 'Aston Villa vs Tottenham',
    gameweek: 35,
    date: '2026-05-05',
    homeTeam: 'Aston Villa',
    awayTeam: 'Tottenham Hotspur',
    homeColor: '#670E36',
    awayColor: '#132257',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'A Villa win widens the gap to safety.',
    spursSurviveContext:   'Spurs need points to jump out of the bottom three.',
  },
  {
    id: 'gw35-everton-man-city',
    label: 'Everton vs Man City',
    gameweek: 35,
    date: '2026-05-05',
    homeTeam: 'Everton',
    awayTeam: 'Manchester City',
    homeColor: '#003399',
    awayColor: '#6CABDD',
    helpsArsenalTitle:   'home',
    helpsCityTitle:      'away',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'An Everton upset hands the title boost to Arsenal.',
    cityTitleContext:    'City must win at Goodison to stay on top.',
    spursRelegatedContext: 'No relegation angle.',
    spursSurviveContext:   'No relegation angle.',
  },

  // ── GW36 – May 10 & 12 ───────────────────────────────────────────────────
  {
    id: 'gw36-man-city-brentford',
    label: 'Man City vs Brentford',
    gameweek: 36,
    date: '2026-05-10',
    homeTeam: 'Manchester City',
    awayTeam: 'Brentford',
    homeColor: '#6CABDD',
    awayColor: '#e30613',
    helpsArsenalTitle:   'away',
    helpsCityTitle:      'home',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'A Brentford upset gives Arsenal the advantage.',
    cityTitleContext:    'City home win is non-negotiable for the title.',
    spursRelegatedContext: 'No relegation angle.',
    spursSurviveContext:   'No relegation angle.',
  },
  {
    id: 'gw36-west-ham-arsenal',
    label: 'West Ham vs Arsenal',
    gameweek: 36,
    date: '2026-05-12',
    homeTeam: 'West Ham United',
    awayTeam: 'Arsenal',
    homeColor: '#7A263A',
    awayColor: '#EF0107',
    helpsArsenalTitle:   'away',
    helpsCityTitle:      'home',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'Arsenal win keeps their title dream alive.',
    cityTitleContext:    'City hope West Ham can take points off Arsenal.',
    spursRelegatedContext: 'West Ham win keeps them ahead of Spurs.',
    spursSurviveContext:   'Arsenal win keeps West Ham in Spurs\' reach.',
  },
  {
    id: 'gw36-tottenham-leeds',
    label: 'Tottenham vs Leeds',
    gameweek: 36,
    date: '2026-05-12',
    homeTeam: 'Tottenham Hotspur',
    awayTeam: 'Leeds United',
    homeColor: '#132257',
    awayColor: '#FFCD00',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'away',
    helpsSpursSurvive:   'home',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'A home loss here is likely curtains for Spurs.',
    spursSurviveContext:   'Must-win home game for Spurs survival.',
  },

  // ── GW37 – May 18 ────────────────────────────────────────────────────────
  {
    id: 'gw37-bournemouth-man-city',
    label: 'Bournemouth vs Man City',
    gameweek: 37,
    date: '2026-05-18',
    homeTeam: 'AFC Bournemouth',
    awayTeam: 'Manchester City',
    homeColor: '#DA291C',
    awayColor: '#6CABDD',
    helpsArsenalTitle:   'home',
    helpsCityTitle:      'away',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'City dropping points here could hand Arsenal the title.',
    cityTitleContext:    'City must navigate this tricky away trip.',
    spursRelegatedContext: 'No relegation angle.',
    spursSurviveContext:   'No relegation angle.',
  },
  {
    id: 'gw37-arsenal-burnley',
    label: 'Arsenal vs Burnley',
    gameweek: 37,
    date: '2026-05-18',
    homeTeam: 'Arsenal',
    awayTeam: 'Burnley',
    homeColor: '#EF0107',
    awayColor: '#6C1D45',
    helpsArsenalTitle:   'home',
    helpsCityTitle:      'away',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'Expected home win to keep the pressure on City.',
    cityTitleContext:    'Burnley upset would be a City miracle.',
    spursRelegatedContext: 'No relegation angle.',
    spursSurviveContext:   'No relegation angle.',
  },
  {
    id: 'gw37-chelsea-tottenham',
    label: 'Chelsea vs Tottenham',
    gameweek: 37,
    date: '2026-05-18',
    homeTeam: 'Chelsea',
    awayTeam: 'Tottenham Hotspur',
    homeColor: '#034694',
    awayColor: '#132257',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'Chelsea win almost certainly sends Spurs down.',
    spursSurviveContext:   'Spurs win at the Bridge would be legendary survival.',
  },
  {
    id: 'gw37-newcastle-west-ham',
    label: 'Newcastle vs West Ham',
    gameweek: 37,
    date: '2026-05-18',
    homeTeam: 'Newcastle United',
    awayTeam: 'West Ham United',
    homeColor: '#241F20',
    awayColor: '#7A263A',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'away',
    helpsSpursSurvive:   'home',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'West Ham win extends their lead over Spurs.',
    spursSurviveContext:   'Newcastle win pulls West Ham back into the scrap.',
  },

  // ── Rescheduled – May 23 ────────────────────────────────────────────────
  {
    id: 'gw31-man-city-palace',
    label: 'Man City vs Palace',
    gameweek: 31,
    date: '2026-05-23',
    homeTeam: 'Manchester City',
    awayTeam: 'Crystal Palace',
    homeColor: '#6CABDD',
    awayColor: '#1B458F',
    helpsArsenalTitle:   'away',
    helpsCityTitle:      'home',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'A Palace shock would hand the title initiative to Arsenal.',
    cityTitleContext:    'City must win their game in hand to stay ahead.',
    spursRelegatedContext: 'No relegation implications.',
    spursSurviveContext:   'No relegation implications.',
  },

  // ── GW38 – May 25 – FINAL DAY ────────────────────────────────────────────
  {
    id: 'gw38-crystal-palace-arsenal',
    label: 'Crystal Palace vs Arsenal',
    gameweek: 38,
    date: '2026-05-25',
    homeTeam: 'Crystal Palace',
    awayTeam: 'Arsenal',
    homeColor: '#1B458F',
    awayColor: '#EF0107',
    helpsArsenalTitle:   'away',
    helpsCityTitle:      'home',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'Final Day win is essential for Arsenal title.',
    cityTitleContext:    'City pray Palace can pull off a miracle.',
    spursRelegatedContext: 'No relegation implications.',
    spursSurviveContext:   'No relegation implications.',
  },
  {
    id: 'gw38-man-city-aston-villa',
    label: 'Man City vs Aston Villa',
    gameweek: 38,
    date: '2026-05-25',
    homeTeam: 'Manchester City',
    awayTeam: 'Aston Villa',
    homeColor: '#6CABDD',
    awayColor: '#670E36',
    helpsArsenalTitle:   'away',
    helpsCityTitle:      'home',
    helpsSpursRelegated: 'neither',
    helpsSpursSurvive:   'neither',
    arsenalTitleContext: 'Villa win hands the title to Arsenal.',
    cityTitleContext:    'City win confirms them as champions.',
    spursRelegatedContext: 'No relegation implications.',
    spursSurviveContext:   'No relegation implications.',
  },
  {
    id: 'gw38-tottenham-everton',
    label: 'Tottenham vs Everton',
    gameweek: 38,
    date: '2026-05-25',
    homeTeam: 'Tottenham Hotspur',
    awayTeam: 'Everton',
    homeColor: '#132257',
    awayColor: '#003399',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'away',
    helpsSpursSurvive:   'home',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'Everton win confirms Spurs relegation.',
    spursSurviveContext:   'Spurs win confirms survival.',
  },
  {
    id: 'gw38-west-ham-leeds',
    label: 'West Ham vs Leeds',
    gameweek: 38,
    date: '2026-05-25',
    homeTeam: 'West Ham United',
    awayTeam: 'Leeds United',
    homeColor: '#7A263A',
    awayColor: '#FFCD00',
    helpsArsenalTitle:   'neither',
    helpsCityTitle:      'neither',
    helpsSpursRelegated: 'home',
    helpsSpursSurvive:   'away',
    arsenalTitleContext: 'No title implications.',
    cityTitleContext:    'No title implications.',
    spursRelegatedContext: 'West Ham survive, likely at Spurs\' expense.',
    spursSurviveContext:   'Leeds win pulls West Ham under if Spurs win.',
  },
];

export function getActiveMatches(today?: string): Match[] {
  // Use provided date or actual current local date in YYYY-MM-DD format
  let now = today;
  if (!now) {
    const d = new Date();
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    now = `${year}-${month}-${day}`;
  }
  return REMAINING_MATCHES.filter(m => m.date > now);
}
